### ISSUE TITLE
Basic checklist before launch

### ISSUE THREAD

**Issue by jeanlucaslima** [marmitadigital/saopaulo.serverlessdays.io#3]
# Basics

- [ ] `favicon`
- [ ] Light and dark themes are working
- [ ] SEO ready
- [ ] Images are optimized 
- [ ] Build steps are working
- [ ] Contact e-mail is working
- [ ] Remove search from template
- [ ] Mobile compatibility
- [ ] CTA for ticket 
- [ ] Speakers list
- [ ] Sponsors list
- [ ] Address for the venue
- [ ] Call for papers external link

# Nice to have and extra content

- [ ] Add timeline and main dates #2 
- [ ] Speakers page detail
- [ ] Map with address and what is around
- [ ] Button for external calendar reminder
- [ ] Sponsors post details
- [ ] Blog
- [ ] English lang support
- [ ] Spanish lang support
